pyhocon/__init__.py, tests/test_config_parser.py
Support list of dicts in parser.
example:
```json
"somekey": [
{"this": "is", "valid": "json"},
{"and it": "must", "be": "supported"}
]
```
=> List of dicts

.travis.yml, README.md, pyhocon/__init__.py, pyhocon/config_tree.py, pyhocon/tool.py, tests/test_config_parser.py, tox.ini
Added changes which make this library Python 2.7 and 3.4 compatible to the extent that is covered by unit tests.
`iter*` methods are removed because there are no `iter*` methods on a dictionary in Python 3.x so there was no trivial solution for compatibility. These methods could have been used by someone for performance reasons, but I believe it is very unlikely, because it is quite cumbersome to access nested values using `iter*` methods.
=> Add python 3 support

pyhocon/__init__.py, pyhocon/config_tree.py, tests/test_config_tree.py
This:
- simplifies the code
- adds useful missing methods e.g. to support iteration
- improves interoperability with other libraries, for example the standard logging lib
=> Make ConfigTree subclass OrderedDict

pyhocon/config_tree.py, tests/test_config_tree.py
I tried to parse `./samples/database.conf`, but I got following error.
```python
File "/usr/local/lib/python2.7/site-packages/pyhocon/config_tree.py", line 66, in _get
raise ConfigMissingException("No configuration setting found for key {key}".format(key='.'.join(key_path[:key_index + 1])))
pyhocon.exceptions.ConfigMissingException: No configuration setting found for key resolver
```
This exception was raised when ConfigTree's `_get` method get `None` value, regardless of whether undefined key or the hocon setting `key = null`.
So I implemented `UndefinedKey` object instead of `None` when unknown key is specified.
=> Fix getting null bug

pyhocon/__init__.py, pyhocon/config_tree.py, pyhocon/tool.py, tests/test_config_parser.py, tests/test_config_tree.py, tests/test_tool.py
these expressions should be considered as invalid
```
d [5]
d {f: 5} {}
d ${a}
```
but the followings are valid:
```
d {
f: 5
}
e {}
```
=> Dict assignment fix

pyhocon/__init__.py, pyhocon/tool.py
- Add `-v, --verbosity` argument to commandline tool
- Default to not log but one can increase verbosity by adding multiple `-v`
- `-v` will log ERROR
- `-vv` will log INFO
- `-vvv` will log DEBUG
When including pyhocon into other projects, logging can be configured per module:
```
pyhocon:
level: "DEBUG"
propagate: 0
pyhocon.config_tree:
level: "WARN"
propagate: 1
```
=> Add logging support

pyhocon/__init__.py, tests/test_config_parser.py
This allows included files to properly reference keys that are defined
in an including file. From the HOCON spec:
Substitution processing is performed as the last parsing step, so a
substitution can look forward in the configuration. If a
configuration consists of multiple files, it may even end up
retrieving a value from another file.
This change has the possibility of breaking configuration files. For
example:
foo.conf:
{ x: 10, y: ${x} }
bar.conf:
include "foo.conf"
x: 42
Prior to this change, the output of pyhocon is:
{
"x": 42,
"y": 10
}
because the value of `y` is looked up immediately after `foo.conf` is
parsed.
After this change, the output of pyhocon is:
{
"x": 42,
"y": 42
}
This matches what the reference java implementation produces.
This change does not address "fixing up" as …
=> Resolve substitutions only after all files have been loaded.

pyhocon/config_parser.py, pyhocon/config_tree.py, pyhocon/tool.py, tests/test_config_parser.py
This should resolve #39 
```
d = OrderedDict()
d['banana'] = 3
d['apple'] = 4
d['pear'] = 1
d['orange'] = 2
config = ConfigFactory.from_dict(d)
assert config == d
or:
d = {
'banana': 3,
'apple': 4,
'pear': 1,
'orange': 2,
}
config = ConfigFactory.from_dict(d)
assert config == d
```
=> added from_dict method

pyhocon/config_parser.py, pyhocon/config_tree.py, pyhocon/tool.py, tests/test_config_parser.py, tests/test_tool.py
I changed the input path in the test to a unicode string which reproduced the bug for 2.x interpreters. As a fix I flipped the instance check condition around.
Out of curiosity I tried unicode string in other places and found more issues. I will try to fix those as well and report back soon.
=> fixed string instance check in with_fallback method (Issue #44)

pyhocon/tool.py
Previously the example usage of the tool in README.md would generate errors.
This trivial change removes those issues.
This was initially introduced in revision e7a6184
=> Fixed command line option parsing to use a default indent of 2.

setup.py
=> Adding argparse as a dependency if being installed on Python 2.6.

pyhocon/__init__.py, pyhocon/config_parser.py, pyhocon/config_tree.py, setup.py, tests/test_tool.py, tox.ini
=> Pycparsing update

pyhocon/config_parser.py, tests/test_config_parser.py
Fixes following error when trying to include an unreadable or invalid URL:
```
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhocon/config_parser.py", line 185, in include_config
obj = ConfigFactory.parse_URL(url, resolve=False)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyhocon/config_parser.py", line 73, in parse_URL
fd.close()
UnboundLocalError: local variable 'fd' referenced before assignment
```
=> handle unreachable URL include

pyhocon/config_tree.py, tests/test_config_parser.py
The [doc](https://github.com/typesafehub/config/blob/master/HOCON.md#array-and-object-concatenation) says:
> For objects, "concatenation" means "merging", so the second object overrides the first.
My understanding is that this refers to the [Duplicate keys and object merging](https://github.com/typesafehub/config/blob/master/HOCON.md#duplicate-keys-and-object-merging) section in the documentation, which requires recursive merging of objects.
My [experiments](https://gist.github.com/gilles-duboscq/06846f931c3eedd45ab81ec6fb1bb1f1) with the Java version also seem to support this interpretation of the specs.
=> Use recursive merging when concatenating objects

pyhocon/config_parser.py, pyhocon/config_tree.py, tests/test_config_parser.py
Fix for #75:
Move wrapping to `ConcatenatedValueParser`.
Previous behaviour could lead to incorrect double nesting of lists when `transform`ing during `final_fixup`.
=> `ConfigValue.transform`: do not wrap lists

CHANGELOG.md, README.md, pyhocon/config_parser.py, pyhocon/config_tree.py, tests/test_config_parser.py
This PR merges changes by @sanzinger that implement self-referential substitutions and the += operator.
The changes are a bit large so they are probably better reviewed commit by commit.
This would fix #35
=> Self-references and += operator

pyhocon/config_tree.py, pyhocon/tool.py, tests/test_config_parser.py, tests/test_config_tree.py, tests/test_tool.py
This fixes conversion to HOCON where keys containing dots would not be quoted.
It also add a `ConfigTree.as_plain_ordered_dict` method. The goal there is to easily get an `OrderedDict` with no special behaviour for `__getitem__` and plain keys (not quoted when they contain a `.`). This helps when passing the tree to some code that doesn't expect special cases for `.` in keys.
=> Key with dots

setup.py
We keep getting dependency issues because some people will upgrade their pyparsing version and pyhocon blows up. I ran the tests on pyparsing 2.1.4 and 2.0.3 and it still works so there is no reason to lock the requirement to 2.1.1. Assuming pyparsing follows semantic versioning properly we should be good.
=> Don't lock pyparsing to a specific version

pyhocon/config_tree.py, setup.py, tests/test_config_parser.py, tests/test_config_tree.py
Changes the behavior of `ConfigTree.get_boo()` to adhere to the HOCON API recommendations.
Ensures that Boolean values can be read from the environment.
* Correcting str<->bool conversion logic
* Unit tests for str<->bool conversion logic
* Parser level unit test for reading environment variables
* Bumped version (patch)
=> Bug fix for ConfigTree.get_bool()

pyhocon/config_parser.py
When `len(token) == 2`, `token[0]` contains the key/field name. `token[1]` is the filename. The type check should be `token[1]`.
@kbakba Could you have a look?
=> fix include file error

pyhocon/config_parser.py, tests/test_config_parser.py
When key contains unicode char, the parser will throw error.
The change is including:
* Able to specify the file encoding in `ConfigFactory.parse_file()`
* Use `codecs.open`to replace built-in `open()`
* Add **alphas8bit** variable for dict key.
=> Fix unicode dict key

pyhocon/config_parser.py
pyhocon officially supports Python 2.6, so it can't use the {} syntax in format strings ([which was added in 2.7](https://docs.python.org/2/library/string.html#format-string-syntax)). This is the only instance in the code.
Admittedly, I don't know what input would hit this case, so I cannot create a test case for it (It is one of the few lines not currently in the code coverage).
=> Fixed Python 2.6 incompatible format string

pyhocon/config_tree.py, pyhocon/exceptions.py, tests/test_config_tree.py
Hi there,
I've added a pop() method to the ConfigTree class, and I'm 99% sure that I've done it correctly.  Wanted to submit a pull request so that I don't have to keep patching locally.  :-)  I tried to cover all the edge cases in the test case, but I may have miss something.
Additionally, I added KeyError to the inheritance list for ConfigMissingException so that you can use it more like a dictionary, like:
```python
c = ConfigTree()
..
try:
v = c['my.key']
except KeyError:
do_something()
```
The only thing I'm not entirely sure of is line 225-227.  It works, although I wasn't sure if you guys had a more preferred way to split/join key names
My commit msg:
> Added pop() method to ConfigTree that works like dict.pop().  Added test
cases as well
>
> Also, appended KeyError to …
=> Added pop() method to ConfigTree and added KeyError to ConfigMissingException

pyhocon/config_tree.py, tests/test_config_tree.py
`pop(key, default)` should remove the key even when its value equals the default
https://docs.python.org/3/library/stdtypes.html#dict.pop
I added a test that would have caught this.
(all of the `test_tool.py` tests fail for me even before I made any changes, so I don't know what I'm doing wrong there, but the new `test_config_tree.py` test passes)
=> ConfigTree.pop() should delete key when value == default_value

.travis.yml, pyhocon/tool.py, tests/test_tool.py, tox.ini
This commit fixes handling NoneValue error with Python 3.6.
Original error is here: https://gist.github.com/chezou/7ffa23821188c02c55f148812df171bf
Fix #122
=> Handle NoneValue for converting methods.

pyhocon/config_parser.py, pyhocon/config_tree.py, tests/test_config_parser.py
Update: it is necessary to handle backtracking the entire chain of overriden_value, e.g.,
```
a.b = 1
a.b = ${a.b}
a.b = ${a.b}
```
The initial fix did not handle backtracking beyond one level. In order to handle this case, it seems easier to merge in PR #144 that exposes the ConfigValues in the overriden_value list. This supersedes PR #144.
```
a.b = 3
a.b = ${a.b}
a.c = [1]
a.c = ${a.c}
a.c = ${a.c}
a.c = ${a.c}
a.d = {foo:bar}
a.d = ${a.d}
a.d = ${a.d}
a.d = ${a.d}
a.d = ${a.d}
```
In `ConfigParser.resolve_substitutions()`, we don't backtrack if the `substitution.parent is resolved.value` is `True`, i.e, the resolved value of the substitution is the originating ConfigValues. HOCON spec says to try to backtrack.
=> Issue 145: backtrack to handle self-references(includes #110)

pyhocon/config_parser.py, tests/test_config_parser.py
Currently we end up with a ConfigTree w/o substitutions but one untransformed ConfigValues.
Add an additional fixup step and test
Addresses issue #125
=> Issue 125: complex substitution

pyhocon/config_tree.py
Support using attributes to access key
```python
conf = ConfigFactory.parse_file('databases.conf')
print conf.databases.mysql.password
```
=> ADD: support attribute way to access key

pyhocon/config_tree.py, tests/test_config_parser.py
If the  key is in the top layer and base layer, save the base value as the overriden_value
Addresses #154
=> Unresolved optional substitutions work with config merging

pyhocon/config_tree.py, tests/test_config_parser.py
When merging a non-root ConfigTree onto a root ConfigTree create history of element if it does not exist.
=> Fix non-root ConfigTree merge onto root ConfigTree

pyhocon/config_parser.py, tests/test_config_parser.py
=> fixed: escape sequences handling

pyhocon/config_parser.py, tests/test_config_parser.py
Passing a reference to ConfigValue instead of copy results in unexpected mutation.
Addresses #157.
=> Fix issue 157: make a copy ConfigValue

pyhocon/config_parser.py, tests/test_config_parser.py
pyhocon does not support numbers in scientific format. related to issue #176
=> Support scientific expression of number

pyhocon/config_parser.py, samples/aws.conf, tests/test_config_parser.py
This PR resolves https://github.com/chimpler/pyhocon/issues/182. According to the HOCON specification, the following characters are forbidden within an unquoted string:
```
['$', '"', '{', '}', '[', ']', ':', '=', ',', '+', '#', '`', '^', '?', '!', '@', '*', '&']
```
These characters will no longer generate a valid unquoted string.
=> Forbidden characters

pyhocon/config_tree.py
This fixes issue #180 "get_int() and get_float() don't raise ConfigException if
wrong type". Calling get_int() and get_float() on a key that is not accepted
by int() or float() would result in TypeError or ValueError instead of
ConfigException. These cases are now handled.
=> Fix raising of ConfigException for get_int() and get_float() #180

pyhocon/converter.py, tests/test_tool.py
As also mentioned by Ivan@renardeinside on gitter, I encountered this bug and made a fix for it (plus a test):
Hi everyone.
I found something strange in HOCONConverter.convert(config,"hocon").
Probably i haven't enough understanding, but if you want to convert come config with unresolved substitution, you got strange result.
Suppose, you have file like this
`parameter = ${substition.v1}`
Then you parse this file and you won't resolve substitution:
`config = ConfigFactory.parse_file("example.conf",resolve=False)`
Then if you convert this config you got this result code:
`print(HOCONConverter.convert(config,"hocon"))`
output:
`parameter = [ConfigValues: [ConfigSubstitution: substition.v1]]`
But probably the result should be:
`parameter = ${substition.v1}`
=> Handle ConfigValues and ConfigSubstitution in HOCONConverter.to_hocon

pyhocon/config_tree.py, tests/test_config_tree.py
I tried to implement conversion of numerically-index objects to arrays.
Tell me if there's even a little mistake. 
https://github.com/lightbend/config/blob/master/HOCON.md#conversion-of-numerically-indexed-objects-to-arrays
=> Supoort conversion of numerically-index objects to arrays

pyhocon/config_tree.py, tests/test_config_tree.py
When using a key that contains special characters, the pyhocon generated is invalid. For example:
```
config_tree = ConfigTree()
escaped_key = f"\"test&key\""
key = f"{escaped_key}"
config_tree.put(key, "value")
hocon_tree = HOCONConverter.to_hocon(config_tree)
```
Which generates a pyhocon:
```
test&key: value
```
This PR attempts to alleviate the issue with allowing double quoted strings as keys when they contain a special character. The full list of special characters can be seen here: https://github.com/lightbend/config/blob/master/HOCON.md#unquoted-strings
I could not manage to make a concise fix while also supporting special characters: `{,"`, as those would require some sort of escaping.
I am not entirely sure whether keys with these characters are even supported within the HOCON …
=> Do not unquote keys containing special characters

pyhocon/converter.py
This is a fix for https://github.com/chimpler/pyhocon/issues/174
It leverages the std json lib to handle properly escaping strings when converting to json.
`python setup.py test` passes
=> Use std json library to fix json string escaping.

MANIFEST.in
They are needed for running tests when pulling the package from PyPi.
I'm not sure this is *all* that's needed, but I figure it's a good start. :)
=> Add samples to MANIFEST.in/sdist

pyhocon/config_parser.py, tests/test_config_parser.py
This PR fixes issue https://github.com/chimpler/pyhocon/issues/213 . 
Essentially, I was blocked by not being able to import an environment variable verbatim into a pyhocon config. I.e. if I have an environment variable `MYVAR=123`, the following `test.conf` failed:
```
MYVAR=${MYVAR}
```
or 
```
MYVAR=${?MYVAR}
```
The only workaround was to assign it to another variable and then handle it as a special case in code. Or to introduce another extra env var into production systems. It is difficult to do so, since they are configuration settings, and people have to be educated on them.
This PR fixes the issue by looking for environment variables when fixing up self references.
=> Fix self references when environment variables exist

pyhocon/config_parser.py, tests/test_config_parser.py
This PR applies the suggested fix from https://github.com/chimpler/pyhocon/issues/187 and adds a test for it as well.
Seems to work on my machine.
@chimpler
=> Fix required(file()) syntax

README.md, pyhocon/config_parser.py, setup.py, tests/test_config_parser.py
In our company, we want to deploy config files as part of Python packages, so we can versionize these. Therefor we would like to include assets from packages in hocon config files. This PR adds the ability to do so.
=> Add support for package include

README.md
The [gitter channel](https://gitter.im/chimpler/pyhocon?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) history has five people, each asking one question, receiving a total of zero responses.
Since it's clearly not an active discussion forum, let's remove it from the README so people won't waste their time posting there.
=> Remove inactive Gitter channel from README

tests/test_config_parser.py
The include substitution doesn't work according to the specs.
Add a test using the example in the spec to demonstrate that.
https://github.com/lightbend/config/blob/master/HOCON.md#include-semantics-substitution
=> Add test for include substitution

pyhocon/config_parser.py, tests/test_config_parser.py
There were 2 problems:
* `$` was used without the `re.MULTILINE` flag thus forcing the end of the stream. 
The duration was parsed only if it was on the last line.
* Regex engine prefers first match when a group of strings with OR operator is given.
  If the input string is `months` and the regex is `m|month|months` the
  math is `m` and the rest `onths` is left to the other parsers.
It should be enough just to sort the strings by the length. `months` will match and should be
correctly extracted from the token stream.
As I am running Python 3.8 some tests are failing. It should be, however, working just fine on 3.7.
There were 2 tests I had to update. Both of them contain a value of `128m` that was previously parsed as a string.
Now it will be parsed as duration. As a workaround, I …
=> Fix parsing of durations/periods

pyhocon/config_parser.py, setup.py, tests/test_config_parser.py
Currently we use the [`asset`](https://pypi.org/project/asset/) library in exactly [one place](https://github.com/chimpler/pyhocon/blob/c2fba83fb5a681342ebcfa5a74b53e6b02d9c459/pyhocon/config_parser.py#L352) to figure out the path to a file inside an installed module. The `asset` library is GPL licensed and brings with it a few more GPL dependencies. As pyhocon is Apache licensed, this causes issues for pyhocon users that cannot include software with strong copyleft licenses like the GPL.
Also, it introduces a lot of transitive dependencies:
```
pyhocon==0.3.56
- asset [required: Any, installed: 0.6.13]
- aadict [required: >=0.2.2, installed: 0.2.3]
- six [required: >=1.6.0, installed: 1.15.0]
- globre [required: >=0.1.5, installed: 0.1.5]
- six [required: >=1.10.0, installed: 1.15.0]
- …
```
=> Rewrite the logic to resolve package-relative paths so we can remove the "asset" library

.travis.yml, pyhocon/config_parser.py, setup.py, tox.ini
The library is compatible with Python 3.9. I just enabled the tests in Tox and added a classifier string.
The second improvement is a fix for: https://github.com/chimpler/pyhocon/issues/248
=> Add support for Python 3.9 and fix deprecation warning

pyhocon/config_parser.py, tests/test_config_parser.py
There are two changes:
* Replace regex with `pyparsing` objects. Most important is `Or()` operator that matches the longest match.
* Fix a bug in `ListParser.postParse()` that ignored some object types.
This fixes: https://github.com/chimpler/pyhocon/issues/252
=> Fix duration parsing in lists

pyhocon/config_parser.py, pyhocon/config_tree.py, tests/test_config_parser.py
Fixing #256 - and a small radius around it.
Using hocon in a larger system where this came up.
```
keys: { something: "${lookup}-${name}" }
overridden by:
keys: { something: "${lookup}-legacy-name" }
```
During substitution & replacement, the following happened:
Starting queue had these substitutions: [${lookup}(parent), ${name}(parent), ${lookup}(child)]
1. Process `${lookup}(parent)`, the result value still had -${name}, so this substitution stays in the set to re-process, and enqueues ${name}(2) at the end of the list.
2. Process `${name}(parent)` - this produces a static result string, and is removed.
3. Process `${lookup}(child)` - this produces a static result string, and is removed.
(that's all the substitutions, so the loop restarts)
4. Process `${lookup}(parent)` - overwrites …
=> #256 - Process substitution overrides in order

pyhocon/config_tree.py, tests/test_config_tree.py
The main difference is that with a fallback you merge the 2 configs into a super config.
With a resolve you only fill in the keys that where are not resolved in the config file.
=> adding the resolve method to resolve substitution keys in 1 config tree with another config tree

pyhocon/config_parser.py
imp.find_module can't find namespace package, update to importlib to resolve package path
=> Resolve namespace package

setup.py
Update `pyparsing` `install_requires` lock in `setup.py` to be more strict and prevent installing `pyparsing>=3` when installing `pyhocon`.
The recent `pyparsing` [v3 release ](https://github.com/pyparsing/pyparsing/releases/tag/pyparsing_3.0.0b3) dropped support for Python 3.5. Without this change, running `pyhocon` on Python 3.5 can result in `SyntaxError` errors.
=> Update pyparsing requires lock to be more strict

setup.py
Do so only for Python 3 since pyparsing 3 dropped support for Python 2
Replaces https://github.com/chimpler/pyhocon/pull/276
=> Update pyparsing requirement from ~=2.0 to >=2,<4

pyhocon/config_parser.py, tests/test_config_parser.py
Closes #272 
In `ConfigTreePatser.postParse()`, where the value is put to the resulting dict, the key was not split. Thus, `ConfigTree.put()` was overwriting any values.
* Added tests for that case
* `ConfigTreePatser.postParse()` now splits the key before calling `ConfigTree.put()`
=> #272: Fixes for dict substitution

pyhocon/converter.py, tests/test_config_parser.py, tests/test_tool.py
* `HOCONConverter.__escape_string() / .escape_match()` methods are now protected instead of private
* Temporary files are closed before being passed to the library
(and then carefully deleted)
* Temporary file names are properly escaped
* `file://` URLs are properly escaped by using `urllib.pathname2url()`
* When writing a file with a multiline string, now uses binary IO instead of text IO to prevent line breaks mess
=> Fix: Tests on Windows

pyhocon/config_parser.py, tests/test_config_parser.py
Trying to fix https://github.com/chimpler/pyhocon/issues/271 and similiar issues once again. Added some tests and make them pass. Did NOT check 4 inlude tests since they're not working on Win.
=> Fix broken overrides

pyhocon/config_parser.py, tests/test_config_parser.py
Added support for triple quoted keys (`"""key""": value` or `"""key""" = value`) and added new test cases
=> Added support for triple quoted keys

pyhocon/config_parser.py, samples/substitutions.d/base.conf, samples/substitutions.d/child.conf, tests/test_config_parser.py
This PR fixes #321, where substitutions are not correctly resolved when nested in subsections and having dependents from another config file.
=> fix(config_parser): handle substitutions with resolved values of type ConfigValues

pyhocon/period_parser.py, tests/test_config_parser.py
periods were not correctly parsed with recent versions of pyparsing because of usage of White()
White is actually not needed, added some tests to avoid issues detected in #324
=> fix(#324): avoid parsing improperly periods on several lines with recent pyparsing versions
