chimpler/pyhocon

.travis.yml, pyhocon/config_tree.py, setup.py, tests/test_config_tree.py, tox.ini
=> Add python 2.6 support

CHANGELOG.md, README.md, pyhocon/__init__.py, pyhocon/config_tree.py, pyhocon/tool.py, setup.py, tests/test_config_parser.py
Support things like:
```
t=[5]
a=$t [7]
```
and
```
t={a:5}
a=$t {b:6}
```
=> Dict and list inheritance

pyhocon/__init__.py, pyhocon/config_tree.py, tests/test_config_parser.py
=> String substitution fix

pyhocon/config_tree.py, tests/test_config_parser.py
Fixed dict merge and added unit tests around it
=> fixed dict merge

pyhocon/__init__.py, pyhocon/config_tree.py, tests/test_config_parser.py, tests/test_tool.py
Fixed the following issues:
* `[{1, 2} ${a}]`
* `[include "test.conf"]`
=> Merging of list of dictionaries

pyhocon/__init__.py, tests/test_config_parser.py
=> added assignments starting with eol

pyhocon/__init__.py
Suppress `IOError` when parsing `include file(...)`
=> Fixes #24 - silent IOError

pyhocon/config_tree.py, tests/test_config_parser.py
=> fixed optional substitional not override when not overriding values at the same level

pyhocon/config_tree.py, tests/test_config_parser.py
Bug example attached to unittest.
=> Fix dotted notation merge

pyhocon/config_parser.py, tests/test_config_parser.py
Fix where missing eol on the last line makes parsing fail
=> Dos chars fix

pyhocon/config_parser.py, pyhocon/config_tree.py, tests/test_config_parser.py
See https://github.com/chimpler/pyhocon/issues/64
=> Bugfix for nested substitution failure, issue #64

pyhocon/config_parser.py, tests/test_config_parser.py
Should fix #39. Sorry for the delay :cry:
=> fixed from_dict according to @zanhsieh

pyhocon/config_parser.py, tests/test_config_parser.py
This merges some fixes from @sanzinger for the case where `resolve_substitutions` is called after merging non-resolved configs.
=> Fixes for self-reference resolution after merging configs

pyhocon/config_parser.py, tests/test_config_parser.py
=> Include fix

pyhocon/config_tree.py, tests/test_config_parser.py
I'm not sure I got all instances of the problem, but it's at least a starting place.
Fixes #98
=> Fixed some error handling that was unable to deal with unicode keys

pyhocon/config_tree.py, setup.py, tests/test_config_tree.py
Added `contains` method for #97
=> Contains method

.travis.yml, pyhocon/config_tree.py, tox.ini
=> config tree fix for pop

pyhocon/config_parser.py
Add option to create a root ConfigTree from dict
Addresses issue #137
=> Issue 137: from_dict option to create as root ConfigTree

pyhocon/__init__.py, pyhocon/config_parser.py, pyhocon/config_tree.py, pyhocon/converter.py, tests/test_config_parser.py
=> Revert "Allow unresolved substitutions to be set to a value or keep ${value}"

pyhocon/config_parser.py, tests/test_config_parser.py
fixed bug where float are parsed as int. Also integrated fix from @ch…unyang-wen to be part of number parsing
=> fixed bug where float are parsed as int

pyhocon/config_tree.py, tests/test_config_tree.py
=> Fix: 'None' instead of 'NoneValue' in '.items()'

pyhocon/config_parser.py
fixes #190
@darthbear Add a context when changing default white chars.
=> Modify: add context for changing default chars

README.md, pyhocon/config_parser.py, setup.py, tests/test_config_parser.py, tox.ini
added partial implementation of hocon duration and period recommended api
=> added partial implementation of hocon duration and period recommended api

pyhocon/config_tree.py
Fix STR_SUBSTITUTION, because ConfigSubstitution has no function raw_str
=> String substitution

pyhocon/converter.py
the file of include, key has chinese string, pyhocon -f json error,fix it.
https://github.com/chimpler/pyhocon/issues/239
=> fix include error
